networks:
  homelab:
    external: true

services:
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest-arm
    container_name: nfs-server
    restart: always
    privileged: true
    environment:
      - SHARED_DIRECTORY=/exports
      - PERMITTED=192.168.6.*
    volumes:
      - /Volumes/backup-data/nfs-share:/exports:rw
    ports:
      - "2049:2049"