networks:
  homelab:
    external: true

volumes:
  icloudpd_config:
    name: icloudpd_config

services:
  icloudpd:
    container_name: icloudpd
    networks:
      - homelab
    environment:
      - TZ=Asia/Shanghai
    image: boredazfcuk/icloudpd
    healthcheck:
      test: /usr/local/bin/healthcheck.sh
      start_period: 30s
    restart: always
    volumes:
      - icloudpd_config:/config
      - ./icloudpd.conf:/config/icloudpd.conf
      - /Volumes/sakamoto-data/media/Photo/icloudpd/shelken:/home/shelken/iCloud/
    deploy:
      replicas: 0
  icloudpd2:
    container_name: icloudpd2
    networks:
      - homelab
    environment:
      - TZ=Asia/Shanghai
    image: icloudpd/icloudpd:latest
    restart: always
    command: 
      - icloudpd
      - --directory /data
      - --username ${APPLE_ID}
      - --cookie-directory /config
      - --domain cn
      - --no-progress-bar
      - --size original
      - --keep-unicode-in-filenames true
      - --auto-delete
      - --folder-structure {:%Y/%m/%d}
      - --log-level debug
      - --watch-with-interval 3600
      - --mfa-provider webui
      - --password-provider webui
    ports:
      - "5123:8080"
    volumes:
      - ${DOCKER_DATA_DIR}/icloudpd/config:/config
      - /Volumes/sakamoto-data/media/Photo/icloudpd/shelken:/data
    deploy:
      replicas: 1
