networks:
  homelab:
    external: true

services:
  cloudflare-ddns:
    image: hotio/cloudflareddns:latest@sha256
    container_name: ddns
    restart: always
    user: "1000:1000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - CF_APITOKEN=${CF_APITOKEN}
      - DETECTION_MODE=${DETECTION_MODE:-curl-ipw.cn}
      - INTERVAL=300
      - LOG_LEVEL=3
      - CF_HOSTS=${CF_HOSTS}
      - CF_ZONES=${CF_ZONES}
      - CF_RECORDTYPES=${CF_RECORDTYPES}
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
        order: stop-first
      restart_policy:
        condition: on-failure
        max_attempts: 1