version: "3.8"
services:
  example:
    image: example
    container_name: example
    depends_on:
      - example
    networks:
      - homelab
    # network_mode: host
    restart: unless-stopped
    command: 'bash'
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - homepage.group=未分类
      - homepage.name=example
      - homepage.icon=docker-moby.png
      - homepage.href=http://${DEPLOY_HOST:-127.0.0.1}:80
      - homepage.description=example
      - homepage.widget.type=example
      - homepage.widget.url=http://${DEPLOY_HOST:-127.0.0.1}:80
      - homepage.widget.key=example
      - "traefik.http.services.example.loadbalancer.server.port=80"
      - "traefik.http.routers.example.service=example"
      - "traefik.http.routers.example.rule=Host(`example.${HOME_DOMAIN}`)"
      - "traefik.enable=true"
      - "traefik.http.routers.example.entrypoints=https"
      - "traefik.http.routers.example.tls=true"
      - "traefik.http.routers.example.tls.certresolver=myresolver"
      - "traefik.http.routers.example.tls.domains[0].main=${HOME_DOMAIN}"
      - "traefik.http.routers.example.tls.domains[0].sans=*.${HOME_DOMAIN}"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - "${DATA_DIR}:/data"
    ports:
      - '80:80'
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
        order: stop-first
      restart_policy:
        condition: on-failure
        max_attempts: 1

networks:
  homelab:
    driver: bridge