networks:
  mosdns-net:
    driver: bridge

services:
  mosdns:
    image: ghcr.io/shelken/mosdns:latest
    container_name: mosdns
    networks:
      - mosdns-net
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - homepage.group=网络
      - homepage.name=mosdns
      - homepage.icon=azure-dns.png
      # - homepage.href=http://${DEPLOY_HOST:-127.0.0.1}:5533
      - homepage.description=dns服务
    environment:
      TZ: Asia/Shanghai
    # volumes:
      # - ${MOSDNS_DATA_DIR}/mosdns/config:/etc/mosdns
      # - mosdns-log:/logs:rw
    ports:
      - "53:53/udp"
      # - "8338:8338/tcp"
      # - "5533:53/tcp"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
        order: stop-first
      restart_policy:
        condition: on-failure
        max_attempts: 3
    logging:
      options:
        max-size: "80m"
        max-file: "3"
