networks:
  homelab:
    external: true

services:
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    user: ${UID:?UID}:${GID:?GID}
    networks:
      - homelab
    # network_mode: host
    command: "server /data --console-address :9001"
    restart: always
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - "${MINIO_DATA_DIR:?MINIO_DATA_DIR}:/data"
    ports:
      - '9001:9001'
      - '9000:9000'
    deploy:
      replicas: 1
