version: '3.8'

networks:
  homelab:
    driver: bridge

services:
  bytebase:
    image: bytebase/bytebase:2.11.1
    container_name: bytebase
    networks:
      - homelab
    restart: unless-stopped
    command: --data /var/opt/bytebase --port 8080
    labels:
      - com.centurylinklabs.watchtower.enable=false
      - homepage.group=未分类
      - homepage.name=bytebase
      - homepage.icon=https://cdn.jsdelivr.net/gh/bytebase/bytebase@main/frontend/src/assets/logo-icon.svg
      - homepage.href=http://${DEPLOY_HOST:-127.0.0.1}:5678
      - homepage.description=bytebase
    environment:
      TZ: Asia/Shanghai
    volumes:
      - "${BYTEBASE_DATA_DIR}:/var/opt/bytebase"
    ports:
      - '5678:8080'
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
        order: stop-first
      restart_policy:
        condition: on-failure
        max_attempts: 1
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    restart: unless-stopped
    networks:
      - homelab
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=0 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=0 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - "${DOCKER_PROXY_HOST:-127.0.0.1}:2575:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
        order: stop-first
      restart_policy:
        condition: on-failure
        max_attempts: 1
  scrypted:
    image: koush/scrypted
    container_name: scrypted
    network_mode: host
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - homepage.group=智能家居
      - homepage.name=scrypted
      - homepage.icon=scrypted.png
      - homepage.href=https://${DEPLOY_HOST:-127.0.0.1}:10443
      - homepage.description=scrypted
    environment:
      TZ: Asia/Shanghai
      SCRYPTED_WEBHOOK_UPDATE: http://localhost:10444/v1/update
      SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION: Bearer SET_THIS_TO_SOME_RANDOM_TEXT
    volumes:
      - "${SCRYPTED_DATA_DIR}:/server/volume"
    # ports:
    #   - '80:80'
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
        order: stop-first
      restart_policy:
        condition: on-failure
        max_attempts: 1
